name: react build
on: 
  push:                               
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04 
    steps:
      - name: repository checkout
        uses: actions/checkout@master

      - name: install dependency
        run: npm install

      - name: build react
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY_ID }}      
        run: aws s3 cp --recursive build s3://kh-bucket --acl public-read