name: my frist github actions
on: 
  push:                           
    branches:
      - master

jobs:
  my-frist-job:
    runs-on: ubuntu-18.04
    steps:
      - name: 에코 테스트 ~!
        run: echo "Hello1"

      - name: ls 테스트 ~!    
        run: ls -al